MYSQL_URL=jdbc:mysql://localhost:3307/tp_appraisal?serverTimezone=UTC
MYSQL_USER=root
MYSQL_PASSWORD=I@mR00t
MYSQL_EMPLOYEE_TABLE=ap_useraccount
MYSQL_ROLE_TABLE=ap_role
MYSQL_LOGIN_TABLE=ap_login
MYSQL_USERROLES_TABLE=ap_user_roles