MYSQL_URL=jdbc:mysql://localhost:3307/tp_bi?serverTimezone=UTC
MYSQL_USER=root
MYSQL_PASSWORD=I@mR00t
MYSQL_EMPLOYEE_TABLE=tp_bi_employee
MYSQL_ROLE_TABLE=tp_bi_role
MYSQL_LOGIN_TABLE=tp_bi_login
MYSQL_USERROLES_TABLE=tp_bi_userroles
CONVERT_TO_CSV_FILEPATH=/opt/CSVFiles_BI/
FILEPATH_TO_STORE_UPLOADEDFILE=/opt/CSVFiles_BI/