MYSQL_URL=jdbc:mysql://localhost:3307/tp_hr?serverTimezone=UTC
MYSQL_USER=root
MYSQL_PASSWORD=I@mR00t
MYSQL_EMPLOYEE_TABLE=hr_employee
MYSQL_ROLE_TABLE=hr_role
MYSQL_LOGIN_TABLE=hr_login
MYSQL_USERROLES_TABLE=hr_user_roles
MYSQL_LOCATION_TABLE=hr_location
MYSQL_DEPARTMENT_TABLE=hr_department
MYSQL_JOBCODE_TABLE=hr_job
CONVERT_TO_CSV_FILEPATH=/opt/CSVFiles_HRSoft/